### PR TITLE
Mustard

### PR DESCRIPTION
**Pull request by iainmcampbell**
I’ve implemented the mustard cutting approach I did for Quipu. There are some pretty significant differences to the gulpfile.

I think the only thing I’ve broken is injecting the SVG files into the `dist/index.html`. @dansundy how was that being done? did the SVG end up being inlined?

### CODE REVIEW

**Comment by dansundy** [comment]
Yes, it was using the same `inject` task.

**Comment by dansundy** [comment]
@iainmcampbell Is this ready to merge (ie. SVGs fixed) or was I supposed to do that?

**Comment by iainmcampbell** [comment]
I haven’t fixed the SVGs yet. I was going to but it slipped my mind. if you have some time feel free to look into it. we can probably just use gulp-inject as you had it before, but just for the svg defs.

**Comment by iainmcampbell** [comment]
@dansundy I’ve restored the svg injection functionality. will merge shortly.

**Comment by iainmcampbell** [comment]
also I worked out a better way of getting around our npm issues here at the office that doesn't require that clunky tar file. will scrub it from the repo history once we merge this branch.

**Comment by dansundy** [comment]
Cool! Let me know if you run into any snags merging into master.

**Pull request merged**
